import { BarItem, ImportProduct } from "./barBackTypes";

export const startingItems: BarItem[] = [
  {
    id: 1,
    productName: "Tito’s Vodka",
    category: "Liquor",
    bottleCost: 28,
    bottleSize: "750mL",
    pourSize: 1.5,
    menuPrice: 7.5,
    drinkCost: 1.66,
    costPercent: 22.1,
    profit: 5.84,
    targetInventory: 6,
    currentInventory: 2,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
    averageOrdered: 4,
    averageRemaining: 1,
    lastPriceReview: "2025-12-01",
    pricingAlertDismissed: false,
  },
  {
    id: 2,
    productName: "House Cabernet",
    category: "Wine",
    bottleCost: 14,
    bottleSize: "750mL",
    pourSize: 5,
    menuPrice: 8,
    drinkCost: 2.8,
    costPercent: 35,
    profit: 5.2,
    targetInventory: 8,
    currentInventory: 3,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
    averageOrdered: 5,
    averageRemaining: 2,
    lastPriceReview: "2026-01-05",
    pricingAlertDismissed: false,
  },
  {
    id: 3,
    productName: "Bud Light Keg",
    category: "Beer",
    bottleCost: 115,
    bottleSize: "1/2 Barrel",
    pourSize: 16,
    menuPrice: 4,
    drinkCost: 0.91,
    costPercent: 22.8,
    profit: 3.09,
    targetInventory: 2,
    currentInventory: 1,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
    averageOrdered: 1,
    averageRemaining: 0,
    lastPriceReview: "2026-02-01",
    pricingAlertDismissed: false,
  },
  {
    id: 4,
    productName: "High Noon Case",
    category: "Cans/Bottles",
    bottleCost: 42,
    bottleSize: "24 Pack",
    pourSize: 1,
    menuPrice: 6,
    drinkCost: 1.75,
    costPercent: 29.2,
    profit: 4.25,
    targetInventory: 5,
    currentInventory: 5,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
    averageOrdered: 2,
    averageRemaining: 2,
    lastPriceReview: "2025-11-20",
    pricingAlertDismissed: false,
  },
];

export const importProducts: ImportProduct[] = [
  { name: "Absolut Vodka", category: "Liquor" },
  { name: "Jack Daniel’s", category: "Liquor" },
  { name: "Bacardi Superior", category: "Liquor" },
  { name: "Josh Cabernet", category: "Wine" },
  { name: "Kendall-Jackson Chardonnay", category: "Wine" },
  { name: "Bud Light Keg", category: "Beer" },
  { name: "Guinness Keg", category: "Beer" },
  { name: "Corona Bottles", category: "Cans/Bottles" },
  { name: "High Noon Case", category: "Cans/Bottles" },
];