import { PantryItem } from "./PantryInventory";

export const mockPantryItems: PantryItem[] = [
  {
    id: 1,
    itemName: "Chicken Breast",
    category: "Protein",
    vendor: "Sysco",
    caseCost: 129,
    caseSize: 40,
    caseUnit: "lb",
    currentInventory: 46,
    targetInventory: 80,
    inventoryUnit: "lb",
    orderQuantity: 1,
    inventoryReviewed: false,
  },
  {
    id: 2,
    itemName: "Mozzarella Cheese",
    category: "Dairy",
    vendor: "US Foods",
    caseCost: 42,
    caseSize: 10,
    caseUnit: "lb",
    currentInventory: 6,
    targetInventory: 12,
    inventoryUnit: "lb",
    orderQuantity: 1,
    inventoryReviewed: true,
  },
  {
    id: 3,
    itemName: "Romaine Lettuce",
    category: "Produce",
    vendor: "Fresh Point",
    caseCost: 38,
    caseSize: 24,
    caseUnit: "each",
    currentInventory: 18,
    targetInventory: 24,
    inventoryUnit: "each",
    orderQuantity: 1,
    inventoryReviewed: false,
  },
  {
    id: 4,
    itemName: "Frozen French Fries",
    category: "Frozen",
    vendor: "Sysco",
    caseCost: 58,
    caseSize: 30,
    caseUnit: "lb",
    currentInventory: 76,
    targetInventory: 80,
    inventoryUnit: "lb",
    orderQuantity: 1,
    inventoryReviewed: false,
  },
  {
    id: 5,
    itemName: "Wing Sauce",
    category: "Sauce",
    vendor: "Restaurant Depot",
    caseCost: 72,
    caseSize: 6,
    caseUnit: "gallon",
    currentInventory: 2,
    targetInventory: 6,
    inventoryUnit: "gallon",
    orderQuantity: 1,
    inventoryReviewed: true,
  },
];