import { BarItem } from "./barBackTypes";

export const startingItems: BarItem[] = [
  {
    id: 1,
    productName: "Tito's Vodka",
    category: "Liquor",
    currentInventory: 2.5,
    targetInventory: 6,
    averageOrdered: 4,
    averageRemaining: 2,
    bottleCost: 23.75,
    bottleSize: 25.36,
    pourSize: 1.5,
    drinkCost: 1.41,
    menuPrice: 8,
    profit: 6.59,
    costPercent: 17.63,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 2,
    productName: "Jameson Irish Whiskey",
    category: "Liquor",
    currentInventory: 1.5,
    targetInventory: 4,
    averageOrdered: 3,
    averageRemaining: 1,
    bottleCost: 31.5,
    bottleSize: 25.36,
    pourSize: 1.5,
    drinkCost: 1.86,
    menuPrice: 9,
    profit: 7.14,
    costPercent: 20.67,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 3,
    productName: "Bacardi Superior",
    category: "Liquor",
    currentInventory: 0.5,
    targetInventory: 3,
    averageOrdered: 2,
    averageRemaining: 1,
    bottleCost: 18.99,
    bottleSize: 25.36,
    pourSize: 1.5,
    drinkCost: 1.12,
    menuPrice: 7,
    profit: 5.88,
    costPercent: 16,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 4,
    productName: "Captain Morgan",
    category: "Liquor",
    currentInventory: 2,
    targetInventory: 3,
    averageOrdered: 2,
    averageRemaining: 1,
    bottleCost: 21.25,
    bottleSize: 25.36,
    pourSize: 1.5,
    drinkCost: 1.26,
    menuPrice: 8,
    profit: 6.74,
    costPercent: 15.75,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 5,
    productName: "Casamigos Blanco",
    category: "Liquor",
    currentInventory: 0.75,
    targetInventory: 2,
    averageOrdered: 1,
    averageRemaining: 1,
    bottleCost: 42.99,
    bottleSize: 25.36,
    pourSize: 1.5,
    drinkCost: 2.54,
    menuPrice: 11,
    profit: 8.46,
    costPercent: 23.09,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 6,
    productName: "Bud Light",
    category: "Beer",
    currentInventory: 18,
    targetInventory: 48,
    averageOrdered: 24,
    averageRemaining: 12,
    bottleCost: 1.1,
    bottleSize: 1,
    pourSize: 1,
    drinkCost: 1.1,
    menuPrice: 4,
    profit: 2.9,
    costPercent: 27.5,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 7,
    productName: "Coors Light",
    category: "Beer",
    currentInventory: 12,
    targetInventory: 48,
    averageOrdered: 24,
    averageRemaining: 12,
    bottleCost: 1.05,
    bottleSize: 1,
    pourSize: 1,
    drinkCost: 1.05,
    menuPrice: 4,
    profit: 2.95,
    costPercent: 26.25,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 8,
    productName: "High Noon Vodka Seltzer",
    category: "Cans/Bottles",
    currentInventory: 10,
    targetInventory: 24,
    averageOrdered: 12,
    averageRemaining: 6,
    bottleCost: 2.25,
    bottleSize: 1,
    pourSize: 1,
    drinkCost: 2.25,
    menuPrice: 6,
    profit: 3.75,
    costPercent: 37.5,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 9,
    productName: "House Chardonnay",
    category: "Wine",
    currentInventory: 3,
    targetInventory: 8,
    averageOrdered: 5,
    averageRemaining: 3,
    bottleCost: 12.5,
    bottleSize: 25.36,
    pourSize: 5,
    drinkCost: 2.46,
    menuPrice: 8,
    profit: 5.54,
    costPercent: 30.75,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
  {
    id: 10,
    productName: "House Cabernet",
    category: "Wine",
    currentInventory: 2,
    targetInventory: 8,
    averageOrdered: 5,
    averageRemaining: 2,
    bottleCost: 13.75,
    bottleSize: 25.36,
    pourSize: 5,
    drinkCost: 2.71,
    menuPrice: 8,
    profit: 5.29,
    costPercent: 33.88,
    lastPriceReview: "2026-05-01",
    pricingAlertDismissed: false,
    inventoryReviewed: false,
    eventAddEnabled: false,
    eventAdd: 0,
  },
];